### ISSUE TITLE
Error: Could not find or load main class org.openqa.grid.selenium.GridLauncher

### ISSUE THREAD

**Issue by ghost** [aimmac23/selenium-video-node#11]
I have the latest versions of selenium server (2.44.0) and video node (1.5). But when I try to start selenium server as hub or node, I get an error: Error: Could not find or load main class org.openqa.grid.selenium.GridLauncher.

![djam-30 12 2014-12 45 53](https://cloud.githubusercontent.com/assets/3090102/5577461/80245ae0-9022-11e4-855e-532a415a8f2f.png)

**Comment by aimmac23** [comment]
Hi Dmitri,

No worries - I keep getting caught out by that too. I've moved the information about Windows classpath separators closer to where its needed :)

Thanks,

Alasdair
