### ISSUE TITLE
Blank video when Hub and Node started as Windows Service

### ISSUE THREAD

**Issue by vsmakse** [aimmac23/selenium-video-node#18]
Hi,

I have started Hub and Node as windows service and ran my test cases. But final video recorded has dark screen.

**Comment by aimmac23** [comment]
Hi vsmakse,

I understand that when Windows runs a desktop application as a service or in a disconnected RDP session, Windows may choose not to render any output. The video recording a black screen is correct behaviour, if a bit unfortunate.

Googling "selenium running as windows service" seems to imply that later versions of windows (Vista/Server 2008) have something called "Session 0 isolation", where services CAN create windows, but are never seen, and probably never drawn.

Your use-case may work under earlier versions of windows - if you can find a copy. However, the Selenium project explicitly don't support running as a service, so I don't recommend it.

I recommend either starting the Selenium node in an RDP session (and make sure the RDP client never disconnects), or creating some Windows VMs and starting up a node in a VNC session.

Unfortunately, there's no known workaround that can be applied to the project to make video recording work as a Windows service - sorry.

Thanks,

Alasdair

**Comment by luker2** [comment]
@aimmac23 same issue on my windows grid vms, although screenshots work fine. Is this because screenshots are somehow taken via the driver (chromedriver) vs. the videos being full desktop captures? It appears this way because the failure screenshots we capture during tests only capture the portion within the Chrome window.

This is outside the project, but since screenshots work regardless of RDP, would it ever make sense to capture a bunch of screenshots during the test and render them into a video?

Our organization requires running tests on Windows Chrome so looking for a way around this black screen.

**Comment by aimmac23** [comment]
I've put a few commits on a branch. The idea seems to to mostly work, with a few issues:
 
- I'm not sure screenshots can be taken concurrently with driver commands - at least for page loads the screenshot call waits until the Selenium command returns. It might be the commands are queuing, or simply can't run concurrently (implemented in Javascript?).
 - Screenshot resolution/video resolution - not entirely sure how this should work, so I've assumed the video resolution is the same as the screen size, and the screenshot gets resized in many/all cases.
 - Performance - highly dependent on the web driver implementation for taking screenshots. Also a bit of time spent in the AWT graphics API to decode/manipulate the PNG, but that can probably be optimised quite a bit.

At the moment I get 2-3 frames per second on my laptop.

**Comment by luker2** [comment]
@aimmac23 Awesome! Sorry I just saw this, I'll have to give it a shot when I get some time to work on our grid again. Could you point out any specific setup/params you had to define to get it running?
