### ISSUE TITLE
Crash while running on docker chrome instance

### ISSUE THREAD

**Issue by danman113** [aimmac23/selenium-video-node#23]
Hello, I'm trying to set up a docker node with selenium. I got it set up so that it works just fine with firefox, but the recording software itself is crashing whenever it starts to record a video. 

It then dumps the following logs:

```
17:01:59.428` INFO - Starting new recording at 15 with resolution 1360x1020
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f80443b97d8, pid=23, tid=140187942078208
#
# JRE version: OpenJDK Runtime Environment (8.0_03-b03) (build 1.8.0_03-Ubuntu-8u77-b03-3ubuntu3-b03)
# Java VM: OpenJDK 64-Bit Server VM (25.03-b03 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x6e7d8]  fwrite+0x18
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid23.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Video stats: width: 1360 height: 1020 bitrate: 0
Aborted
```

I'm using a modified version of [docker-selenium:NodeChrome](https://github.com/SeleniumHQ/docker-selenium/tree/master/NodeChrome)

```
#!/bin/bash

source /opt/bin/functions.sh

export GEOMETRY="$SCREEN_WIDTH""x""$SCREEN_HEIGHT""x""$SCREEN_DEPTH"

if [ ! -e /opt/selenium/config.json ]; then
  echo No Selenium Node configuration file, the node-base image is not intended to be run directly. 1>&2
  exit 1
fi

if [ -z "$HUB_PORT_4444_TCP_ADDR" ]; then
  echo Not linked with a running Hub container 1>&2
  exit 1
fi

function shutdown {
  kill -s SIGTERM $NODE_PID
  wait $NODE_PID
}

REMOTE_HOST_PARAM=""
if [ ! -z "$REMOTE_HOST" ]; then
  echo "REMOTE_HOST variable is set, appending -remoteHost"
  REMOTE_HOST_PARAM="-remoteHost $REMOTE_HOST"
fi

if [ ! -z "$SE_OPTS" ]; then
  echo "appending selenium options: ${SE_OPTS}"
fi

# TODO: Look into http://www.seleniumhq.org/docs/05_selenium_rc.jsp#browser-side-logs
SERVERNUM=$(get_server_num)
xvfb-run -n $SERVERNUM --server-args="-screen 0 $GEOMETRY -ac +extension RANDR" \
  java ${JAVA_OPTS} -cp /opt/selenium/selenium-video-node-1.9.jar:/opt/selenium/selenium-server-standalone.jar org.openqa.grid.selenium.GridLauncher \
    -servlets com.aimmac23.node.servlet.VideoRecordingControlServlet \
    -proxy com.aimmac23.hub.proxy.VideoProxy \
    -Dwebdriver.chrome.driver=/usr/bin/chromedriver \
    -role wd \
    -hub http://$HUB_PORT_4444_TCP_ADDR:$HUB_PORT_4444_TCP_PORT/grid/register \
    ${REMOTE_HOST_PARAM} \
    -nodeConfig /opt/selenium/config.json \
    ${SE_OPTS} &
NODE_PID=$!

trap shutdown SIGTERM SIGINT
wait $NODE_PID
```

Any ideas on what might be going on?

**Comment by aimmac23** [comment]
Hi danman113,

The cause is almost certainly a crash in the native code handling the video encoding.

I don't think there's anything you're doing wrong trying to run it. You could try running it again with " -Djna.debug_load=true". I don't think the native code will work with any other version of libvpx (the video encoder), and it's possible it's using a version from your machine/docker node. If it's not being loaded from the same place as libinterface.so and libyuv.so, then you've found the problem.
 
If that doesn't work I'll try to reproduce your issue - I can't think left-hand what else might be causing your issue.

**Comment by danman113** [comment]
Hello aimmac23, thanks for the prompt response!

I went ahead and ran it with "-Djna.debug_load=true" and the output was the same except for the following lines:
```
Looking in classpath from sun.misc.Launcher$AppClassLoader@1b6d3586 for /com/sun/jna/linux-x86-64/libjnidispatch.so
Found library resource at jar:file:/opt/selenium/selenium-server-standalone.jar!/com/sun/jna/linux-x86-64/libjnidispatch.so
Looking for library 'vpx'
Adding paths from jna.library.path: null
Trying libvpx.so
Adding system paths: [/usr/lib/x86_64-linux-gnu, /lib/x86_64-linux-gnu, /lib64, /usr/lib, /lib]
Trying libvpx.so
Looking for version variants
Trying /usr/lib/x86_64-linux-gnu/libvpx.so.3.0
Found library 'vpx' at /usr/lib/x86_64-linux-gnu/libvpx.so.3.0
Looking for library 'yuv'
Adding paths from jna.library.path: null
Trying /tmp/nativeCode-1466559423741/libyuv.so
Found library 'yuv' at /tmp/nativeCode-1466559423741/libyuv.so
Looking for library 'mkv'
Adding paths from jna.library.path: null
Trying /tmp/nativeCode-1466559423741/libmkv.so
Found library 'mkv' at /tmp/nativeCode-1466559423741/libmkv.so
Looking for library 'interface'
Adding paths from jna.library.path: null
Trying /tmp/nativeCode-1466559423741/libinterface.so
Found library 'interface' at /tmp/nativeCode-1466559423741/libinterface.so
```
I'm not exactly sure where the issue is, it seems to be getting the libraries from the temp folder, which I'm assuming comes from the jar (as you can tell I'm not a java wizard).

I also copied the entire log to [here](https://gist.github.com/danman113/feed7ecc64804c857ae50d3e91cc900bl)

I'm pretty sure that it's not trying to use a local version, so I uploaded the docker things that I'm using so that you can try to get it running on your machine [here](https://github.com/danman113/selenium-video-node-issue/tree/master). The beauty of docker is that the issue _should_ be easy to replicate.

**Comment by aimmac23** [comment]
Hi danman113,

Thanks for the enthusiasm :)

The JNA debugging flag seems to have done the trick - the issue is here:

Trying libvpx.so
Looking for version variants
Trying /usr/lib/x86_64-linux-gnu/libvpx.so.3.0
Found library 'vpx' at /usr/lib/x86_64-linux-gnu/libvpx.so.3.0

Compare the directory above with:

Found library 'yuv' at /tmp/nativeCode-1466559423741/libyuv.so

So its loading the system library version instead of the version bundled with the project. I think I may have used a snapshot version of libvpx (I'm not sure that version was released at the time?), so something about the library may have changed a bit between the two versions.

I'll take a look at it over the weekend - either compiling against the latest version of libvpx-1.3.0, or renaming the version I have and linking against that should do the trick.

**Comment by danman113** [comment]
Thanks a whole lot for looking over this issue. If there's anything I can help with (especially with testing) don't be afraid to ask.

**Comment by aimmac23** [comment]
Hi danman113,

Sorry, I got a bit distracted trying to update the version of libvpx. I've committed a temporary fix to the "issue23" branch, which renames the VPX file to not conflict with the system-provided implementations.

If you don't usually use Maven you can download a copy here:

https://aimmac23.com/public/misc/selenium-video-node-1.10-SNAPSHOT-issue23.jar

That should unblock you from the docker container work while something more permanent is put in place (I think this may have broken either the Windows/OS X support?).

Let me know how if that fixes the problem :)

**Comment by danman113** [comment]
Yup, that did the trick!

Thanks a lot almmac23, good luck getting everything updated.
