### ISSUE TITLE
Getting illegal state exception for node configuration

### ISSUE THREAD

**Issue by hemanthsridhar** [aimmac23/selenium-video-node#28]
VM : Windows Server 2008 R2 Standard
Selenium version : 2.53.1
Selenium-video-node version : 1.9

When I provide **java -cp selenium-video-node-1.9.jar;selenium-server-standalone-2.53.1.jar org.openqa.grid.selenium.GridLauncher -servlets com.aimmac23.node.servlet.VideoRecordingControlServlet -proxy com.aimmac23.hub.proxy.VideoProxy -role node -hub http://localhost:4444/grid/register**

Getting the below exception
```
C:\Users\Hemanth\Softwares>java -cp selenium-video-node-1.9.jar;selenium-server-
standalone-2.53.1.jar org.openqa.grid.selenium.GridLauncher -servlets com.aimmac
23.node.servlet.VideoRecordingControlServlet -proxy com.aimmac23.hub.proxy.Video
Proxy -role node -hub http://localhost:4444/grid/register
04:20:54.912 INFO - Launching a Selenium Grid node
04:20:56.597 INFO - Java: Oracle Corporation 25.112-b15
04:20:56.597 INFO - OS: Windows Server 2008 R2 6.1 amd64
04:20:56.612 INFO - v2.53.1, with Core v2.53.1. Built from revision a36b8b1
04:20:56.753 INFO - Driver class not found: com.opera.core.systems.OperaDriver
04:20:56.753 INFO - Driver provider com.opera.core.systems.OperaDriver is not re
gistered
04:20:56.784 INFO - Driver provider org.openqa.selenium.safari.SafariDriver regi
stration is skipped:
registration capabilities Capabilities [{browserName=safari, version=, platform=
MAC}] does not match the current platform VISTA
04:20:56.784 INFO - Driver class not found: org.openqa.selenium.htmlunit.HtmlUni
tDriver
04:20:56.784 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver
is not registered
04:20:57.704 INFO - Will attempt to record at  15 frames per second - adjust thi
s value  by setting -Dvideo.framerate=<value>
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.openqa.selenium.server.SeleniumServer.createServlet(SeleniumServe
r.java:636)
        at org.openqa.selenium.server.SeleniumServer.registerExtraServlets(Selen
iumServer.java:621)
        at org.openqa.selenium.server.SeleniumServer.<init>(SeleniumServer.java:
256)
        at org.openqa.grid.selenium.GridLauncher$3.launch(GridLauncher.java:91)
        at org.openqa.grid.selenium.GridLauncher.main(GridLauncher.java:127)
Caused by: java.lang.IllegalStateException: Could not create screenshot source f
or video encoder
        at com.aimmac23.node.VideoRecordController.<init>(VideoRecordController.
java:66)
        at com.aimmac23.node.servlet.VideoRecordingControlServlet.<clinit>(Video
RecordingControlServlet.java:47)
        ... 7 more
Caused by: java.lang.IllegalStateException: Display colour depth incorrect (shou
ld be 8 bits of red, blue and green). Currently: 5-6-5
        at com.aimmac23.node.RobotScreenshotSource.doStartupSanityChecks(RobotSc
reenshotSource.java:69)
        at com.aimmac23.node.VideoRecordController.<init>(VideoRecordController.
java:63)
        ... 8 more
```

**Comment by aimmac23** [comment]
Hi hemanthsridhar,

Your display is configured to use 24-bit colour. You'll need to use 32-bit colour to make this work.

If you're using remote desktop to access your server, I've found this link to be helpful:

https://technet.microsoft.com/en-us/library/cc772048(v=ws.11).aspx

Thanks,

Alasdair

**Comment by hemanthsridhar** [comment]
thank you

**Comment by hemanthsridhar** [comment]
@aimmac23 But one more thing, Now I am able to generate the videos. Problem is I am getting blank video for 10 to 15 odd seconds. Configuration is the same.

**Comment by aimmac23** [comment]
Hi hemanthsridhar,

How are you running your Selenium node? As a windows service, RDP session or local login?

You're most likely getting a black screen because Windows isn't rendering anything - this can happen if you try to run something as a Windows service, or if your RDP session disconnects. Maybe even if your local session locks it's screen too.

Alasdair

**Comment by hemanthsridhar** [comment]
Hi.

This is how I did the configuration. 
Went inside the VM
Opened cmd
Started the hub with servlet
Opened cmd
Started the node with the servlet

Regarding RDP session, I have no Idea. 
Screen lock. I highly doubt.

Can you please help me more on this. Any mistake that I have done?

**Comment by aimmac23** [comment]
>  Went inside the VM

How did you go inside the VM? Is it running on your local machine? Is it an AWS instance? How did you access the VM? Were you looking at your server's desktop when you were launching tests?

The rest of the steps you listed look fine - the most likely cause is the Java screenshot functionality failing to get any image data.

**Comment by hemanthsridhar** [comment]
Thanks for your reply. 
I logged in using the remote desktop connection. 
No I was not in my VM when my tests were running.
 
-Hemanth

**Comment by suayipozmen** [comment]
If you close rdp session java robot takes black screenshots. Because display driver quits.
You can install  vnc server on remote. Vnc server starts on boot and display driver never quits.
You should connect only via vnc to control remote machine.

**Comment by hemanthsridhar** [comment]
@aimmac23 If I am in the VM while the tests are running then the video is recorded. If I am out of the VM while the tests are running then the video is blacked out.
Can you please help me with this?

**Comment by suayipozmen** [comment]
@hemanthsridhar did you read my comment?
if you dont want to setup vnc server you can start a local rdp session on vm that connects localhost. however you quit rdp session, display driver use local session.

**Comment by hemanthsridhar** [comment]
@suayipozmen thank you for the reply.

But I am really not able to understand what you are trying to say. I am newbie. Can you give me some steps so that I can follow?
It would be of great help.

Regards,
Hemanth

**Comment by aimmac23** [comment]
Hi hemanthsridhar,

I haven't done it myself, but I think you need to configure a windows user to auto-login at startup, and have that user install something like this (probably through your RDP login):

http://www.tightvnc.com

You then connect to your server through the VNC connection to startup Selenium, rather than RDP.

In the end the blank screen that is being recorded is due to a Microsoft design decision not to render anything when the RDP cannot see it. Since we rely indirectly on Windows APIs to grab the screen contents, there's not much more we can do about the RDP issue - apart from recommending the use of VNC instead.

Good luck,

Alasdair

**Comment by aimmac23** [comment]
I assume the immediate problem has been resolved, so closing issue.

**Comment by hemanthsridhar** [comment]
@aimmac23 thanks
