### ISSUE TITLE
Download stored videos to file

### ISSUE THREAD

**Issue by rab2215** [aimmac23/selenium-video-node#30]
I have been evaluating this library for possible integration into our UI regression test suites and I have been able to successfully link the stored videos to test reports.  Ideally I should be able to embed the file into the report itself instead of relying on the grid hub as a repository.  Is there currently any features in the API to download the videos to file?

**Comment by aimmac23** [comment]
Hi rab2215,

I'm not sure what you mean - if you don't want to use the Hub to store videos long-term, then I would recommend using a different back-end storage system:

https://github.com/aimmac23/selenium-video-node/blob/master/ADDITIONAL_FEATURES.md#video-storage-arguments

I think either LocalFileVideoStore or BasicWebDAVStore may do what you need in this case, depending on how the report is built.

You might also have been asking to embed the video in a report - you probably want an HTML 5 video tag for that:

http://www.w3schools.com/html/html5_video.asp

One of the above answers should hopefully answer your question.

Thanks,

Alasdair

**Comment by rab2215** [comment]
The html reports I use already contain support for screencasts, so embedding the url is fairly straightforward.  I was asking if there was a feature to download the videos locally.  This is important due to the fact that we have quite strict (FDA) requirements on storage of objective evidence for tests per software release.  Downloading the files locally would allow us to store the webm files along with the html reports long term in our already existing repository, which would also prevent the need to validate another storage system.  I have since found a solution that will allow me to do this.

**Comment by aimmac23** [comment]
Hi rab2215,

Sorry in the delay in replying - I'm glad you found a solution. The URL that the hub provides for viewing the videos is also the same URL for downloading the videos - its up to the web browser/report builder/test to save it locally to disk, instead of on the hub.

Alasdair

**Comment by aimmac23** [comment]
rab2215 seems to be happy with his solution, so closing issue.
