### ISSUE TITLE
how to delete video after upload ?

### ISSUE THREAD

**Issue by tahayk** [aimmac23/selenium-video-node#52]
I'm using selenium-video-node version `2.5` (for Selenium 3.6.0 and below), 
I'm wondering how to delete the video from the node after I upload it to S3 ?

**Comment by aimmac23** [comment]
Hi tahaykACF,

At the moment the node only stores up to 5 videos, and deletes them if more are recorded. The videos are also cleared out when the node is shutdown.

If you're using the CloudS3VideoStore then nothing is stored on the Hub - every request calls S3 for data.

Currently there's no way to manually clear out the videos from the node.

Thanks,

Alasdair Macmillan
