### ISSUE TITLE
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':99.0' as the value of the DISPLAY variable

### ISSUE THREAD

**Issue by Niteshsuresh** [aimmac23/selenium-video-node#53]
Hello,

Please help!.

Below is the problem

Using custom Selenium Chrome Node, I try running Video Grid in docker and Selenium Node is failing to execute because of the error 

> Can't connect to X11 window server using ':99.0' as the value of the DISPLAY variable

Below is the docker run command
![screenshot from 2017-12-20 23-25-41](https://user-images.githubusercontent.com/24651771/34221466-1f3187fc-e5de-11e7-97dd-a58608dbd1c6.png)

Below is the failure
![screenshot from 2017-12-20 23-27-36](https://user-images.githubusercontent.com/24651771/34221468-1f72c6f4-e5de-11e7-94ea-5df5dfabf72b.png)

However, If I tried to Display as :0 or :0.0. nothing worked.
But one thing to note is,
If I make Display equal to empty input (i.e. Display=) I'm getting all together different error.

![screenshot from 2017-12-20 23-22-00](https://user-images.githubusercontent.com/24651771/34221703-09f8b4ea-e5df-11e7-8178-1e64c9917025.png)

Below is the Dockfile dump

FROM selenium/node-chrome
USER root
RUN mkdir /root/code
RUN chmod 777 -R /root/code

RUN apt-get update && apt install -y curl

RUN apt-get -y install software-properties-common

### Install Java.
RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java8-installer && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /var/cache/oracle-jdk8-installer

### Define commonly used JAVA_HOME variable
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle

### Needed to compile spring boot our spring boot application
ARG MAVEN_VERSION=3.5.2
ARG USER_HOME_DIR="/root"
ARG SHA=707b1f6e390a65bde4af4cdaf2a24d45fc19a6ded00fff02e91626e3e42ceaff
ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries

RUN mkdir -p /usr/share/maven /usr/share/maven/ref \
  && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
  && echo "${SHA}  /tmp/apache-maven.tar.gz" | sha256sum -c - \
  && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
  && rm -f /tmp/apache-maven.tar.gz \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"

RUN apt-get -qqy install locales xvfb
WORKDIR /root/code

### Selenium Video Hub and Node processes are spawned by application during to startup
ADD FuncWebSGridV /root/code/

ENV java.awt.headless false
CMD mvn spring-boot:run

### Expose ports.
EXPOSE 8082
EXPOSE 4444
EXPOSE 5555

**Comment by aimmac23** [comment]
Hi Niteshsuresh,

That seems a bit odd. You could try the X11 acceleration option, which bypasses the AWT robot:

https://github.com/aimmac23/selenium-video-node/blob/master/ADDITIONAL_FEATURES.md#x11-acceleration-linuxunix-only

If it can't connect to the X server it may end up crashing with an Xlib error - hopefully the error message may be more useful?

Thanks,

Alasdair

**Comment by Niteshsuresh** [comment]
Thank you Alasdair. I have bypassed AWT robot code and everything is working fine.

God bless!

Best Regards
Nitesh
