### ISSUE TITLE
Using CloudS3VideoStore class servlet along with Selenium throws ClassCastException

### ISSUE THREAD

**Issue by saumitthale** [aimmac23/selenium-video-node#55]
I am trying to store videos to Amazon s3 with servlet "com.aimmac23.hub.videostorage.CloudS3VideoStore"

The hub always throws ClasssCastException and fails to initiate both on Linux as well as windows instance. Please check below logs from my windows instance.

Windows Server 2016 64-bit - AWS instance
Java version:- 1.8.0_162

Logs:- 
C:\selenium>java -cp selenium-video-node-2.6.jar;selenium-server-standalone-3.9.1.jar org.openqa.grid.selenium.GridLauncherV3 -servlets com.aimmac23.hub.videostorage.CloudS3VideoStore,com.aimmac23.hub.servlet.HubVideoInfoServlet -role hub
20:48:53.485 INFO - Selenium build info: version: '3.9.1', revision: '63f7b50'
20:48:53.487 INFO - Launching Selenium Grid hub on port 4444
Usage: <main class> [options]
  Options:
    --version, -version
      Displays the version and exits.
      Default: false
    -browserTimeout
      <Integer> in seconds : number of seconds a browser session is allowed to
      hang while a WebDriver command is running (example: driver.get(url)). If
      the timeout is reached while a WebDriver command is still processing,
      the session will quit. Minimum value is 60. An unspecified, zero, or
      negative value means wait indefinitely.
      Default: 0
    -matcher, -capabilityMatcher
      <String> class name : a class implementing the CapabilityMatcher
      interface. Specifies the logic the hub will follow to define whether a
      request can be assigned to a node. For example, if you want to have the
      matching process use regular expressions instead of exact match when
      specifying browser version. ALL nodes of a grid ecosystem would then use
      the same capabilityMatcher, as defined here.
      Default: org.openqa.grid.internal.utils.DefaultCapabilityMatcher@13a5fe33
    -cleanUpCycle
      <Integer> in ms : specifies how often the hub will poll running proxies
      for timed-out (i.e. hung) threads. Must also specify "timeout" option
      Default: 5000
    -custom
      <String> : comma separated key=value pairs for custom grid extensions.
      NOT RECOMMENDED -- may be deprecated in a future revision. Example:
      -custom myParamA=Value1,myParamB=Value2
      Default: {}
    -debug
      <Boolean> : enables LogLevel.FINE.
      Default: false
    -host
      <String> IP or hostname : usually determined automatically. Most
      commonly useful in exotic network configurations (e.g. network with VPN)
      Default: 192.168.0.4
    -hubConfig
      <String> filename: a JSON file (following grid2 format), which defines
      the hub properties
    -jettyThreads, -jettyMaxThreads
      <Integer> : max number of threads for Jetty. An unspecified, zero, or
      negative value means the Jetty default value (200) will be used.
    -log
      <String> filename : the filename to use for logging. If omitted, will
      log to STDOUT
    -maxSession
      <Integer> max number of tests that can run at the same time on the node,
      irrespective of the browser used
    -newSessionWaitTimeout
      <Integer> in ms : The time after which a new test waiting for a node to
      become available will time out. When that happens, the test will throw
      an exception before attempting to start a browser. An unspecified, zero,
      or negative value means wait indefinitely.
      Default: -1
    -port
      <Integer> : the port number the server will use.
      Default: 4444
    -prioritizer
      <String> class name : a class implementing the Prioritizer interface.
      Specify a custom Prioritizer if you want to sort the order in which new
      session requests are processed when there is a queue. Default to null (
      no priority = FIFO )
    -registry
      <String> class name : a class implementing the GridRegistry interface.
      Specifies the registry the hub will use.
      Default: org.openqa.grid.internal.DefaultGridRegistry
    -role
      <String> options are [hub], [node], or [standalone].
      Default: hub
    -servlet, -servlets
      <String> : list of extra servlets the grid (hub or node) will make
      available. Specify multiple on the command line: -servlet
      tld.company.ServletA -servlet tld.company.ServletB. The servlet must
      exist in the path: /grid/admin/ServletA /grid/admin/ServletB
      Default: [com.aimmac23.hub.videostorage.CloudS3VideoStore, com.aimmac23.hub.servlet.HubVideoInfoServlet]
    -timeout, -sessionTimeout
      <Integer> in seconds : Specifies the timeout before the server
      automatically kills a session that hasn't had any activity in the last X
      seconds. The test slot will then be released for another test to use.
      This is typically used to take care of client crashes. For grid hub/node
      roles, cleanUpCycle must also be set.
      Default: 1800
    -throwOnCapabilityNotPresent
      <Boolean> true or false : If true, the hub will reject all test requests
      if no compatible proxy is currently registered. If set to false, the
      request will queue until a node supporting the capability is registered
      with the grid.
      Default: true
    -withoutServlet, -withoutServlets
      <String> : list of default (hub or node) servlets to disable. Advanced
      use cases only. Not all default servlets can be disabled. Specify
      multiple on the command line: -withoutServlet tld.company.ServletA
      -withoutServlet tld.company.ServletB
      Default: []
java.lang.ClassCastException: class com.aimmac23.hub.videostorage.CloudS3VideoStore
        at java.lang.Class.asSubclass(Unknown Source)
        at org.openqa.grid.web.utils.ExtraServletUtil.createServlet(ExtraServletUtil.java:38)
        at org.openqa.grid.web.Hub.<init>(Hub.java:109)
        at org.openqa.grid.selenium.GridLauncherV3$2.launch(GridLauncherV3.java:301)
        at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:117)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:79)

**Comment by aimmac23** [comment]
Hi saumitthale,

Sorry for the delay in replying. I think your command line should be:

java -cp selenium-video-node-2.6.jar;selenium-server-standalone-3.9.1.jar -Dvideo.storage=com.aimmac23.hub.videostorage.CloudS3VideoStore org.openqa.grid.selenium.GridLauncherV3 -servlets com.aimmac23.hub.servlet.HubVideoInfoServlet -role hub

The CloudS3VideoStore is in fact a storage plugin used by the VideoProxy/Servlets, rather than being a servlet itself.

Let me know if you have any further issues.

Alasdair Macmillan

**Comment by saumitthale** [comment]
Hi @aimmac23 
I have updated the command line and its looking good. Thanks for your help.
